/** 移植 internal/css/css.go */

export interface CssOptions {
  fontFamily: string;
  fontSrcs: string[];
  lineHeight: number;
  fontSize: number;
  marginTop: number;
  textAlign: number;
  indent: number;
  /** 用户自定义 CSS 片段，追加在生成 CSS 末尾（优先级最高，可覆盖自动生成的规则） */
  customCss: string;
}

export function defaultCss(partial?: Partial<CssOptions>): CssOptions {
  return {
    fontFamily: "easypub",
    fontSrcs: [],
    lineHeight: 120,
    fontSize: 100,
    marginTop: 5,
    textAlign: 0,
    indent: 0,
    customCss: "",
    ...partial,
  };
}

export function generateCss(o: CssOptions): string {
  if (!o.fontFamily) o.fontFamily = "easypub";
  if (!Number.isFinite(o.lineHeight) || o.lineHeight <= 0) o.lineHeight = 120;
  if (!Number.isFinite(o.fontSize) || o.fontSize <= 0) o.fontSize = 100;
  if (!Number.isFinite(o.textAlign) || o.textAlign < 0 || o.textAlign > 3) o.textAlign = 0;
  if (!Number.isFinite(o.marginTop) || o.marginTop < 0) o.marginTop = 5;
  if (!Number.isFinite(o.indent) || o.indent < 0) o.indent = 0;

  let b = "";
  b += "/*  Generated by EasyPub  */\n";
  b += "/*  此css由EasyPub自动生成  */\n";
  b += "/*  部分参考老牛中文样式  */\n\n";

  b += "@font-face {\n";
  b += `      font-family: "${o.fontFamily}";\n`;
  if (o.fontSrcs.length === 0) {
    b += "      src: local(sans-serif);\n";
  } else {
    b += "      src: ";
    b += o.fontSrcs.map((s) => `url(${s})`).join(",\n           ");
    b += ";\n";
  }
  b += "}\n\n";

  b += "@page { \n";
  b += "      margin-top: 0px;\n";
  b += "      margin-bottom: 0px;\n";
  b += "}\n\n";

  b += "body { \n";
  b += `      font-family: "${o.fontFamily}";\n`;
  b += "      padding: 0;\n";
  b += "      margin-left: 0px;\n";
  b += "      margin-right: 0px;\n";
  b += "      orphans: 0;\n";
  b += "      widows: 0;\n";
  b += "}\n\n";

  b += "p { \n";
  b += `      font-family: "${o.fontFamily}";\n`;
  b += `      font-size: ${o.fontSize}%;\n`;
  b += `      line-height: ${o.lineHeight}%;\n`;
  b += `      margin-top: ${o.marginTop}px;\n`;
  b += "      margin-bottom: 0;\n";
  b += "      margin-left: 0;\n";
  b += "      margin-right: 0;\n";
  b += "      orphans: 0;\n";
  b += "      widows: 0;\n";
  b += "}\n\n";

  // 对齐 Go fmt.Sprintf("%grem")：JS Number.toString 在常规浮点上等价
  // 极小值（如 5e-5）格式分歧，被上游 clamp [0,4] 后用户难以触达
  const indent = o.indent > 0 ? `${o.indent}rem` : "0em";
  b += ".a { \n";
  b += `      text-indent: ${indent};\n`;
  b += "}\n\n";

  b += "div.centeredimage {\n";
  b += "      text-align:center;\n";
  b += "      display:block;\n";
  b += "      margin-top: 0.5em;\n";
  b += "      margin-bottom: 0.5em;\n";
  b += "}\n\n";

  b += "img.attpic {\n";
  b += "      border: 1px solid #000000;\n";
  b += "      max-width: 100%;\n";
  b += "      margin: 0;\n";
  b += "}\n\n";

  b += ".booktitle {\n";
  b += "      margin-top: 30%;\n";
  b += "      margin-bottom: 0;\n";
  b += "      border-style: none solid none none;\n";
  b += "      border-width: 50px;\n";
  b += "      border-color: #4E594D;\n";
  b += "      font-size: 3em;\n";
  b += "      line-height: 120%;\n";
  b += "      text-align: right;\n";
  b += "}\n\n";

  b += ".bookauthor {\n";
  b += "      margin-top: 0;\n";
  b += "      border-style: none solid none none;\n";
  b += "      border-width: 50px;\n";
  b += "      border-color: #4E594D;\n";
  b += "      page-break-after: always;\n";
  b += "      font-size: large;\n";
  b += "      line-height: 120%;\n";
  b += "      text-align: right;\n";
  b += "}\n\n";

  b +=
    ".titletoc, .titlel1top, .titlel1std,.titlel2top, .titlel2std,.titlel3top, .titlel3std,.titlel4std {\n";
  b += "      margin-top: 0;\n";
  b += "      border-style: none double none solid;\n";
  b += "      border-width: 0px 5px 0px 20px;\n";
  b += "      border-color: #586357;\n";
  b += "      background-color: #C1CCC0;\n";
  b += "      padding: 45px 5px 5px 5px;\n";
  b += "      font-size: x-large;\n";
  b += "      line-height: 115%;\n";
  b += "      text-align: justify;\n";
  b += "}\n\n";

  b += ".titlel1single,.titlel2single,.titlel3single {\n";
  b += "      margin-top: 35%;\n";
  b += "      border-style: none solid none none;\n";
  b += "      border-width: 30px;\n";
  b += "      border-color: #4E594D;\n";
  b += "      padding: 30px 5px 5px 5px;\n";
  b += "      font-size: x-large;\n";
  b += "      line-height: 125%;\n";
  b += "      text-align: right;\n";
  b += "}\n\n";

  b += ".toc {\n";
  b += "      margin-left:16%;\n";
  b += "      padding:0px;\n";
  b += "      line-height:130%;\n";
  b += "      text-align: justify;\n";
  b += "}\n\n";

  b += ".toc a { text-decoration: none; color: #000000; }\n\n";

  b += ".tocl1 {\n";
  b += "      margin-top:0.5em;\n";
  b += "      margin-left:-30px;\n";
  b += "      border-style: none double double solid;\n";
  b += "      border-width: 0px 5px 2px 20px;\n";
  b += "      border-color: #6B766A;\n";
  b += "      line-height: 135%;\n";
  b += "      font-size: 132%;\n";
  b += "}\n\n";

  b += ".tocl2 {\n";
  b += "      margin-top: 0.5em;\n";
  b += "      margin-left:-20px;\n";
  b += "      border-style: none double none solid;\n";
  b += "      border-width: 0px 2px 0px 10px;\n";
  b += "      border-color: #939E92;\n";
  b += "      line-height: 123%;\n";
  b += "      font-size: 120%;\n";
  b += "}\n\n";

  b += ".tocl3 {\n";
  b += "      margin-top: 0.5em;\n";
  b += "      margin-left:-20px;\n";
  b += "      border-style: none double none solid;\n";
  b += "      border-width: 0px 2px 0px 8px;\n";
  b += "      border-color: #939E92;\n";
  b += "      line-height: 112%;\n";
  b += "      font-size: 109%;\n";
  b += "}\n\n";

  b += ".tocl4 {\n";
  b += "      margin-top: 0.5em;\n";
  b += "      margin-left:-20px;\n";
  b += "      border-style: none double none solid;\n";
  b += "      border-width: 0px 2px 0px 6px;\n";
  b += "      border-color: #939E92;\n";
  b += "      line-height: 115%;\n";
  b += "      font-size: 110%;\n";
  b += "}\n\n";

  b += ".subtoc {\n";
  b += "      margin-left:15%;\n";
  b += "      padding:0px;\n";
  b += "      text-align: justify;\n";
  b += "}\n\n";

  b += ".subtoclist {\n";
  b += "      margin-top: 0.5em;\n";
  b += "      margin-left:-20px;\n";
  b += "      border-style: none double none solid;\n";
  b += "      border-width: 0px 2px 0px 10px;\n";
  b += "      border-color: #939E92;\n";
  b += "      line-height: 123%;\n";
  b += "      font-size: 120%;\n";
  b += "}\n\n";

  if (o.textAlign !== 0) {
    const align = ["justify", "left", "center", "right"][o.textAlign];
    b += `p, .a { text-align: ${align}; }\n`;
  }

  // 用户自定义 CSS 追加在末尾，优先级最高，可覆盖以上自动生成的规则
  if (o.customCss && o.customCss.trim()) {
    b += "\n/* ===== 用户自定义 CSS ===== */\n";
    b += o.customCss.trim() + "\n";
  }

  return b;
}

export function clampInt(v: number, min: number, max: number, def: number): number {
  if (!Number.isFinite(v)) return def;
  if (v === 0 && def !== 0 && min > 0 && v < min) return def;
  if (v < min) return min;
  if (v > max) return max;
  return v;
}

export function clampFloat(v: number, min: number, max: number, def: number): number {
  if (!Number.isFinite(v)) return def;
  if (v < min) {
    if (v === 0 && def !== 0) return def;
    return min;
  }
  if (v > max) return max;
  return v;
}
