// Package css 根据配置生成 EPUB 内嵌 style.css。
//
// 模板参考自 EasyPub v1.50 输出的 style.css，部分参考老牛中文样式。
// 可被 cssoverwrite / savecss 等选项控制是否覆盖外部 css 目录同名文件。
package css

import (
	"fmt"
	"strings"
)

// Options 控制 style.css 的内容。零值时使用合理默认值。
type Options struct {
	// FontFamily 内嵌 @font-face 的 font-family 名称。
	FontFamily string
	// FontSrcs @font-face 的 src url() 列表，对应 ereaders.xml 中所选阅读器的字体路径。
	FontSrcs []string
	// LineHeight 段落行高(%)，对应 config.lineheight。
	LineHeight int
	// FontSize 段落字号(%)，对应 config.fontsize。
	FontSize int
	// MarginTop 段落 margin-top(px)，对应 config.margintop。
	MarginTop int
	// TextAlign 文本对齐：0=justify(默认),1=left,2=center,3=right。
	TextAlign int
	// Indent 段落首行缩进(em)。若 >0 则覆盖 .a 的 text-indent。
	Indent float64
}

// Default 返回与样例 epub 完全一致的默认配置。
func Default(fontSrcs []string) Options {
	return Options{
		FontFamily: "easypub",
		FontSrcs:   fontSrcs,
		LineHeight: 120,
		FontSize:   100,
		MarginTop:  5,
		TextAlign:  0,
		Indent:     0,
	}
}

// Generate 生成 style.css 全文。结果与样例 epub 的 style.css 字节级一致
// (在默认参数与两段字体路径下)。
func Generate(o Options) string {
	if o.FontFamily == "" {
		o.FontFamily = "easypub"
	}
	if o.LineHeight == 0 {
		o.LineHeight = 120
	}
	if o.FontSize == 0 {
		o.FontSize = 100
	}
	if o.TextAlign < 0 || o.TextAlign > 3 {
		o.TextAlign = 0
	}

	var b strings.Builder
	b.WriteString("/*  Generated by EasyPub  */\n")
	b.WriteString("/*  此css由EasyPub自动生成  */\n")
	b.WriteString("/*  部分参考老牛中文样式  */\n\n")

	// @font-face
	b.WriteString("@font-face {\n")
	b.WriteString(fmt.Sprintf("      font-family: %q;\n", o.FontFamily))
	if len(o.FontSrcs) == 0 {
		b.WriteString("      src: local(sans-serif);\n")
	} else {
		b.WriteString("      src: ")
		for i, s := range o.FontSrcs {
			if i > 0 {
				b.WriteString(",\n           ")
			}
			b.WriteString("url(")
			b.WriteString(s)
			b.WriteString(")")
		}
		b.WriteString(";\n")
	}
	b.WriteString("}\n\n")

	// @page
	b.WriteString("@page { \n")
	b.WriteString("      margin-top: 0px;\n")
	b.WriteString("      margin-bottom: 0px;\n")
	b.WriteString("}\n\n")

	// body
	b.WriteString("body { \n")
	b.WriteString(fmt.Sprintf("      font-family: %q;\n", o.FontFamily))
	b.WriteString("      padding: 0;\n")
	b.WriteString("      margin-left: 0px;\n")
	b.WriteString("      margin-right: 0px;\n")
	b.WriteString("      orphans: 0;\n")
	b.WriteString("      widows: 0;\n")
	b.WriteString("}\n\n")

	// p
	b.WriteString("p { \n")
	b.WriteString(fmt.Sprintf("      font-family: %q;\n", o.FontFamily))
	b.WriteString(fmt.Sprintf("      font-size: %d%%;\n", o.FontSize))
	b.WriteString(fmt.Sprintf("      line-height: %d%%;\n", o.LineHeight))
	b.WriteString(fmt.Sprintf("      margin-top: %dpx;\n", o.MarginTop))
	b.WriteString("      margin-bottom: 0;\n")
	b.WriteString("      margin-left: 0;\n")
	b.WriteString("      margin-right: 0;\n")
	b.WriteString("      orphans: 0;\n")
	b.WriteString("      widows: 0;\n")
	b.WriteString("}\n\n")

	// .a 段落正文样式
	indent := "0em"
	if o.Indent > 0 {
		indent = fmt.Sprintf("%grem", o.Indent)
	}
	b.WriteString(".a { \n")
	b.WriteString(fmt.Sprintf("      text-indent: %s;\n", indent))
	b.WriteString("}\n\n")

	// 图片相关
	b.WriteString("div.centeredimage {\n")
	b.WriteString("      text-align:center;\n")
	b.WriteString("      display:block;\n")
	b.WriteString("      margin-top: 0.5em;\n")
	b.WriteString("      margin-bottom: 0.5em;\n")
	b.WriteString("}\n\n")

	b.WriteString("img.attpic {\n")
	b.WriteString("      border: 1px solid #000000;\n")
	b.WriteString("      max-width: 100%;\n")
	b.WriteString("      margin: 0;\n")
	b.WriteString("}\n\n")

	// 封面
	b.WriteString(".booktitle {\n")
	b.WriteString("      margin-top: 30%;\n")
	b.WriteString("      margin-bottom: 0;\n")
	b.WriteString("      border-style: none solid none none;\n")
	b.WriteString("      border-width: 50px;\n")
	b.WriteString("      border-color: #4E594D;\n")
	b.WriteString("      font-size: 3em;\n")
	b.WriteString("      line-height: 120%;\n")
	b.WriteString("      text-align: right;\n")
	b.WriteString("}\n\n")

	b.WriteString(".bookauthor {\n")
	b.WriteString("      margin-top: 0;\n")
	b.WriteString("      border-style: none solid none none;\n")
	b.WriteString("      border-width: 50px;\n")
	b.WriteString("      border-color: #4E594D;\n")
	b.WriteString("      page-break-after: always;\n")
	b.WriteString("      font-size: large;\n")
	b.WriteString("      line-height: 120%;\n")
	b.WriteString("      text-align: right;\n")
	b.WriteString("}\n\n")

	// 各级标题
	b.WriteString(".titletoc, .titlel1top, .titlel1std,.titlel2top, .titlel2std,.titlel3top, .titlel3std,.titlel4std {\n")
	b.WriteString("      margin-top: 0;\n")
	b.WriteString("      border-style: none double none solid;\n")
	b.WriteString("      border-width: 0px 5px 0px 20px;\n")
	b.WriteString("      border-color: #586357;\n")
	b.WriteString("      background-color: #C1CCC0;\n")
	b.WriteString("      padding: 45px 5px 5px 5px;\n")
	b.WriteString("      font-size: x-large;\n")
	b.WriteString("      line-height: 115%;\n")
	b.WriteString("      text-align: justify;\n")
	b.WriteString("}\n\n")

	b.WriteString(".titlel1single,.titlel2single,.titlel3single {\n")
	b.WriteString("      margin-top: 35%;\n")
	b.WriteString("      border-style: none solid none none;\n")
	b.WriteString("      border-width: 30px;\n")
	b.WriteString("      border-color: #4E594D;\n")
	b.WriteString("      padding: 30px 5px 5px 5px;\n")
	b.WriteString("      font-size: x-large;\n")
	b.WriteString("      line-height: 125%;\n")
	b.WriteString("      text-align: right;\n")
	b.WriteString("}\n\n")

	// TOC
	b.WriteString(".toc {\n")
	b.WriteString("      margin-left:16%;\n")
	b.WriteString("      padding:0px;\n")
	b.WriteString("      line-height:130%;\n")
	b.WriteString("      text-align: justify;\n")
	b.WriteString("}\n\n")

	b.WriteString(".toc a { text-decoration: none; color: #000000; }\n\n")

	b.WriteString(".tocl1 {\n")
	b.WriteString("      margin-top:0.5em;\n")
	b.WriteString("      margin-left:-30px;\n")
	b.WriteString("      border-style: none double double solid;\n")
	b.WriteString("      border-width: 0px 5px 2px 20px;\n")
	b.WriteString("      border-color: #6B766A;\n")
	b.WriteString("      line-height: 135%;\n")
	b.WriteString("      font-size: 132%;\n")
	b.WriteString("}\n\n")

	b.WriteString(".tocl2 {\n")
	b.WriteString("      margin-top: 0.5em;\n")
	b.WriteString("      margin-left:-20px;\n")
	b.WriteString("      border-style: none double none solid;\n")
	b.WriteString("      border-width: 0px 2px 0px 10px;\n")
	b.WriteString("      border-color: #939E92;\n")
	b.WriteString("      line-height: 123%;\n")
	b.WriteString("      font-size: 120%;\n")
	b.WriteString("}\n\n")

	b.WriteString(".tocl3 {\n")
	b.WriteString("      margin-top: 0.5em;\n")
	b.WriteString("      margin-left:-20px;\n")
	b.WriteString("      border-style: none double none solid;\n")
	b.WriteString("      border-width: 0px 2px 0px 8px;\n")
	b.WriteString("      border-color: #939E92;\n")
	b.WriteString("      line-height: 112%;\n")
	b.WriteString("      font-size: 109%;\n")
	b.WriteString("}\n\n")

	b.WriteString(".tocl4 {\n")
	b.WriteString("      margin-top: 0.5em;\n")
	b.WriteString("      margin-left:-20px;\n")
	b.WriteString("      border-style: none double none solid;\n")
	b.WriteString("      border-width: 0px 2px 0px 6px;\n")
	b.WriteString("      border-color: #939E92;\n")
	b.WriteString("      line-height: 115%;\n")
	b.WriteString("      font-size: 110%;\n")
	b.WriteString("}\n\n")

	b.WriteString(".subtoc {\n")
	b.WriteString("      margin-left:15%;\n")
	b.WriteString("      padding:0px;\n")
	b.WriteString("      text-align: justify;\n")
	b.WriteString("}\n\n")

	b.WriteString(".subtoclist {\n")
	b.WriteString("      margin-top: 0.5em;\n")
	b.WriteString("      margin-left:-20px;\n")
	b.WriteString("      border-style: none double none solid;\n")
	b.WriteString("      border-width: 0px 2px 0px 10px;\n")
	b.WriteString("      border-color: #939E92;\n")
	b.WriteString("      line-height: 123%;\n")
	b.WriteString("      font-size: 120%;\n")
	b.WriteString("}\n\n")

	// 文本对齐(覆盖默认 justify)
	if o.TextAlign != 0 {
		align := []string{"justify", "left", "center", "right"}[o.TextAlign]
		// 在 p 与 .a 中注入 text-align
		rule := fmt.Sprintf("p, .a { text-align: %s; }\n", align)
		b.WriteString(rule)
	}

	return b.String()
}
